# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 12:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='片名')),
                ('intro', models.TextField(blank=True, null=True, verbose_name='简洁')),
                ('storage_folder', models.FilePathField(null=True, verbose_name='目录')),
                ('year', models.IntegerField(null=True, verbose_name='年份')),
                ('imdb', models.CharField(max_length=15, null=True)),
                ('douban', models.CharField(max_length=15, null=True)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
        migrations.CreateModel(
            name='MoviePerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patato.Movie')),
            ],
        ),
        migrations.CreateModel(
            name='MovieRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='角色')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
            ],
        ),
        migrations.AddField(
            model_name='movieperson',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patato.Person'),
        ),
        migrations.AddField(
            model_name='movieperson',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patato.MovieRole'),
        ),
        migrations.AddField(
            model_name='aka',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patato.Movie'),
        ),
    ]
