# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patato', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
