# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 07:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patato', '0002_movie_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='类型')),
            ],
        ),
        migrations.CreateModel(
            name='MovieGene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patato.Gene')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patato.Movie')),
            ],
        ),
    ]
