# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patato', '0003_gene_moviegene'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='original_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='原名'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='intro',
            field=models.TextField(blank=True, null=True, verbose_name='简介'),
        ),
    ]
