# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 21:20
from __future__ import unicode_literals

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('patato', '0004_auto_20160621_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='douban',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='imdb',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='storage_folder',
            field=models.FilePathField(blank=True, null=True, verbose_name='目录'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='年份'),
        ),
    ]
