# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patato', '0005_auto_20160621_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='storage_folder',
            field=models.FilePathField(blank=True, null=True, path='C:\\Users\\seanc\\Dev\\Python\\NMM', verbose_name='目录'),
        ),
    ]
